### ISSUE TITLE
Master Thesis Description easier

### ISSUE THREAD

**Issue by fillytoria** [itpplasma/itpplasma.github.io#6]
make it easier to read and more concrete, fix relation to itp homepage (what happens if I google Graz Plasma Master Thesis)

**Comment by fillytoria** [comment]
Done by Chris

**Comment by krystophny** [comment]
Closing as duplicate: this repo is now a redirect stub; the issue belongs to itpplasma/profitUI (same issue number tracked there). See itpplasma/profitUI#6.
